---
# Configuration file for BlockQuests, a quests plugin by BlockHorizons.

# File saving format for quest saving.
# Available providers:
# - yaml
# - json
Quest-Saving-Data-Provider: yaml

# Player quest data storage database.
# Available databases:
# SQLite
# MySQL
Player-Quests-Database: SQLite
...