---
# Configuration file for BlockQuests, a quests plugin by BlockHorizons.

# File saving format for quest saving.
# Available providers:
# - yaml
# - json
Quest-Saving-Data-Provider: yaml

# Player quest data storage database.
# Available databases:
# SQLite
Player-Quests-Database: SQLite

# The format used when starting a new quest.
# {STARTING_MESSAGE}: The message set when creating/editing the quest.
# {QUEST_NAME}: The name of the quest set when creating/editing the quest.
# {QUEST_DESCRIPTION}: The description of the quest also set when creating/editing the quest.
Quest-Starting-Format: "{STARTING_MESSAGE}\nQuest Started: {QUEST_NAME}\n{QUEST_DESCRIPTION}"
...
